# Generated by Django 3.0.3 on 2020-04-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='banner',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
