# Generated by Django 3.0.3 on 2020-06-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200605_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='loc_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
