# Generated by Django 3.0.3 on 2020-04-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200409_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='banner',
            name='width',
            field=models.IntegerField(),
        ),
    ]
