# Generated by Django 3.0.3 on 2020-04-13 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200409_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='device',
            new_name='application',
        ),
    ]
