# Generated by Django 3.0.3 on 2020-06-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200605_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='app_code',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='application',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
