# Generated by Django 3.0.3 on 2020-04-13 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200413_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='app.Application'),
        ),
    ]
