# Generated by Django 3.0.3 on 2020-05-14 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200513_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installation',
            name='code',
        ),
    ]
