# Generated by Django 3.0.3 on 2020-04-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200414_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='is_archived',
        ),
        migrations.AddField(
            model_name='page',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Banner'),
        ),
    ]
