# Generated by Django 3.0.3 on 2020-04-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200422_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
