# Generated by Django 3.0.3 on 2020-04-27 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200425_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installation',
            name='is_active',
        ),
        migrations.AddField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='is_slider',
            field=models.BooleanField(default=False),
        ),
    ]
